version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: staff-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: staff_db
      MYSQL_USER: staff_user
      MYSQL_PASSWORD: staff_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    image: php:8.0-apache
    container_name: staff-php
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: staff-phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
